import Navbar from '@/components/navbar/Navbar';
import SocialIcons  from '@/components/SocialIcons';
import ArrowUp  from '@/components/ArrowUp';
import Head from 'next/head';
import { motion } from "framer-motion";
import Banner from '@/components/Banner';
import Skill from '@/components/skill/Skill';
import Projet from '@/components/projets/Projets';
import Contact from '@/components/contact/Contact';


export default function Home() {
  return (
    <>
      <Head >
        <title>Matthieu corvo </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-screen font-bodyFont bg-bodyColor text-textDark  overflow-x-hidden overflow-y-scroll  ">
    <Navbar/>

    <div className="w-full h-[88vh] xl:flex items-center gap-20 justify-between">
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ delay: 0.5 }}
      className="hidden xl:inline-flex w-32 h-full fixed left-0 bottom-0"
    >
      <SocialIcons />
      </motion.div>
      <div className="h-[88vh] mx-auto p-4">
          <Banner />
          <Skill />
          <Projet />
          <Contact />

      </div>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.5 }}
        className="hidden xl:inline-flex w-32 h-full fixed right-0 bottom-0"
      >
      <ArrowUp /> 
      </motion.div>
        </div>
    </main>
    </>
  )
}
